name: "checkov check the terraform module"
description: checkov init and check

runs:
  using: "composite"
  steps:
    - name: Run checkov action
      # https://github.com/bridgecrewio/checkov-action
      uses: bridgecrewio/checkov-action@master
      continue-on-error: true
      with:
        directory: infra/module
        framework: terraform
        container_user: 1000

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif
        category: checkov

