name: "checkov check the terraform module"
description: checkov init and check

runs:
  using: "composite"
  steps:
    - name: Run checkov action
      # https://github.com/bridgecrewio/checkov-action
      uses: bridgecrewio/checkov-action@master
      continue-on-error: true
      with:
        directory: infra/module
        framework: terraform
        container_user: 1000

    - name: Fetch action
      id: fetch
      uses: Rishabh510/Path-lister-action@master
      with:
        path: "."
        type: ".sarif"

    - name: Output results
      shell: bash
      run: |
        echo "Found ${{ steps.fetch.outputs.path_count }} file(s) with this extension:"
        for i in ${{ steps.fetch.outputs.paths }}; do
        echo $i
        done

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif
        category: checkov

