name: "terrascan check the terraform module"
description: terrascan init and check

runs:
  using: "composite"
  steps:
    - name: setup terrascan
      # https://github.com/tenable/terrascan-action
      uses: tenable/terrascan-action@main
      with:
        iac_type: 'terraform'
        iac_version: 'v14'
        policy_type: 'aws'
        only_warn: true
        iac_dir: "./infra/module"
        sarif_upload: true

    - name: Fetch action
      id: fetch
      uses: Rishabh510/Path-lister-action@master
      with:
        path: "."
        type: ".sarif"

    - name: Output results
      shell: bash
      run: |
        echo "Found ${{ steps.fetch.outputs.path_count }} file(s) with this extension:"
        for i in ${{ steps.fetch.outputs.paths }}; do
        echo $i
        done

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: terrascan.sarif
        category: terrascan
