name: "terragrunt plan and apply"
description: terragrunt validate and apply terraform
inputs:
  role-to-assume:
    required: true
    description: "AWS IAM role"
  role-session-name:
    required: true
    description: "AWS IAM role session name"
  apply-terragrunt:
    default: "false"
    description: apply the module or not
    required: true
runs:
  using: "composite"
  steps:
    - name: setup terraform
      uses: hashicorp/setup-terraform@v2
    - name: Setup Terragrunt
      uses: autero1/action-terragrunt@v1.1.0
      with:
        terragrunt_version: 0.37.3

    - name: GitHub OIDC Auth to assume AWS Role
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        role-session-name: ${{ inputs.role-session-name }}

    - name: terragrunt validate
      shell: bash
      run: cd terragrunt && terragrunt run-all validate
    - name: terragunt validate inputs
      shell: bash
      run: cd terragrunt && terragunt validate-inputs --terragrunt-strict-validate
    - name: terragrunt plan
      shell: bash
      run: cd terragrunt && terragrunt run-all plan

    - name: terragrunt apply
      shell: bash
      if: ${{ inputs.apply-terragrunt == "true" }}
      run: cd terragrunt && terragrunt run-all apply


