name: "terragrunt plan and apply"
description: terragrunt validate and apply terraform
inputs:
  role-to-assume:
    required: true
    description: "AWS IAM role"
  role-session-name:
    required: true
    description: "AWS IAM role session name"
  apply-terragrunt:
    default: 'false'
    required: false
    description: apply the module or not
  env:
    required: true
    description: path in terragrunt
  aws-region:
    required: true
    description: path in region

runs:
  using: "composite"
  steps:
    - name: setup terraform
      uses: hashicorp/setup-terraform@v2
      with: 
        terraform_wrapper: false

    - name: Setup Terragrunt
      uses: autero1/action-terragrunt@v1.1.0
      with:
        terragrunt_version: 0.37.3

    - name: GitHub OIDC Auth to assume AWS Role
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        role-session-name: ${{ inputs.role-session-name }}
        aws-region: ${{ inputs.aws-region }}

    - name: terragrunt validate
      shell: bash
      run: cd terragrunt/${{ inputs.env }}/${{ inputs.aws-region }} && terragrunt run-all validate --terragrunt-non-interactive

    - name: terragunt validate inputs
      shell: bash
      run: cd terragrunt/${{ inputs.env }}/${{ inputs.aws-region }} && terragunt validate-inputs --terragrunt-strict-validate
    - name: terragrunt plan
      shell: bash
      run: cd terragrunt/${{ inputs.env }}/${{ inputs.aws-region }} && terragrunt run-all plan

    - name: terragrunt apply
      shell: bash
      if: ${{ inputs.apply-terragrunt == 'true' }}
      run: cd terragrunt/${{ inputs.env }}/${{ inputs.aws-region }} && terragrunt run-all apply -auto-approve


