name: "terragrunt plan and apply"
description: terragrunt validate and apply terraform
inputs:
  aws-audience:
    required: false
    description: "AWS Audience"
    default: sts.amazonaws.com
  role-to-assume:
    required: true
    description: "AWS IAM role"
  role-session-name:
    required: true
    description: "AWS IAM role session name"
  apply-terragrunt:
    default: 'false'
    required: false
    description: apply the terraform module or not
  env-dir:
    required: true
    description: directory with the aws account (mark) folder name
  aws-region:
    required: true
    description: aws region

runs:
  using: "composite"
  steps:
    - name: setup terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Setup Terragrunt
      uses: autero1/action-terragrunt@v1.3.1
      with:
        terragrunt_version: latest
        
    - name: Sops Binary Installer
      uses: mdgreenwald/mozilla-sops-action@v1.4.1
      with:
        version: 'v3.7.3' # default is latest stable

    - name: GitHub OIDC Auth to assume AWS Role
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        role-session-name: ${{ inputs.role-session-name }}
        aws-region: ${{ inputs.aws-region }}
        audience: ${{ inputs.aws-audience }}

    - name: terragrunt validate
      shell: bash
      run: cd terragrunt/${{ inputs.env-dir }}/${{ inputs.aws-region }} && terragrunt run-all validate --terragrunt-non-interactive

    - name: terragrunt plan
      shell: bash
      run: cd terragrunt/${{ inputs.env-dir }}/${{ inputs.aws-region }} && terragrunt run-all plan

    - name: terragrunt apply
      shell: bash
      if: ${{ inputs.apply-terragrunt == 'true' }}
      # https://github.com/gruntwork-io/terragrunt/issues/486
      run: cd terragrunt/${{ inputs.env-dir }}/${{ inputs.aws-region }} && terragrunt run-all apply --terragrunt-non-interactive -auto-approve

