name: 'Deploy Infra'
on:
  push:
    branches:
      - main

jobs:
  init-packages:
    name: init packages
    runs-on: ubuntu-latest
    steps:
      - name: setup terraform
        uses: hashicorp/setup-terraform@v2

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: 0.37.3

      - name: setup terrascan
        # https://github.com/tenable/terrascan-action
        id: terrascan
        uses: tenable/terrascan-action@main
        with:
          iac_type: 'terraform'
          iac_version: 'v14'
          policy_type: 'aws'
          only_warn: true
          sarif_upload: true

      - name: Setup Infracost
        # https://github.com/infracost/actions
        # https://github.com/infracost/actions/tree/master/setup for other inputs
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Run checkov action
        # https://github.com/bridgecrewio/checkov-action
        id: checkov
        uses: bridgecrewio/checkov-action@master

      - uses: actions/cache@v2
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1
        with:
          tflink_version: v0.29.0
#      - name: Setup tfsec
#        uses:


  validate-packages:
    needs: ['init-packages']
    runs-on: ubuntu-latest
    steps:
      - name: checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
#      - name: terragunt validate inputs
#        run: terragunt validate-inputs --terragrunt-strict-validate
#
#      - name: terragrunt validate all
#        run: terragunt run-all validate
#      - name: terrascan
#
#      - name: terragrunt plan all
#        run: terragunt run-all plan
#      - name: terragrunt apply all
#        run: terragunt run-all apply





