name: 'Deploy Infra'
on:
  push:
    branches:
      - main

jobs:
  init-env:
    name: plan
    runs-on: ubuntu-latest
    steps:
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: 0.37.3
      - name: setup terraform
        uses: hashicorp/setup-terraform@v2
      # https://github.com/tenable/terrascan-action
      - name: setup terrascan
        id: terrascan
        uses: tenable/terrascan-action@main
        with:
          iac_type: 'terraform'
          iac_version: 'v14'
          policy_type: 'aws'
          only_warn: true
          sarif_upload: true
          #non_recursive:
          #iac_dir:
          #policy_path:
          #skip_rules:
          #config_path:
          #webhook_url:
          #webhook_token:
      # https://github.com/infracost/actions
      - name: Setup Infracost
      # See https://github.com/infracost/actions/tree/master/setup for other inputs
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
      # https://github.com/bridgecrewio/checkov-action
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master

      - uses: actions/cache@v2
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1
        with:
          tflink_version: v0.29.0
      - name: Setup tfsec
        uses:


  validate:
    needs: ['init-env']
    runs-on: ubuntu-latest
    steps:
      -
        #    - name: checkout
#      uses: actions/checkout@v3
#      with:
#        ref: main
#      - name: terragunt validate inputs
#        run: terragunt validate-inputs --terragrunt-strict-validate
#
#      - name: terragrunt validate all
#        run: terragunt run-all validate
#      - name: terrascan
#
#      - name: terragrunt plan all
#        run: terragunt run-all plan
#      - name: terragrunt apply all
#        run: terragunt run-all apply





