name: 'Deploy prod Infra'
on:
  push:
    branches:
      - main

env:
  role-to-assume: arn:aws:iam::${{ secrets.PROD_AWS_ACCOUNT_ID }}:role/terragrunt
  role-session-name: github-action

jobs:
  terragrunt-action:
    name: init packages
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: init packages
        uses: ./.github/action/terragrunt-action
        with:
          role-to-assume: ${{ env.role-to-assume }}
          role-session-name: ${{ env.role-session-name }}
#  validate-action:
#    permissions:
#      id-token: write
#      contents: read
#    needs: ['init-action']
#    runs-on: ubuntu-latest
#    steps:
#      - name: validate terragrunt modules
#        uses: ./.github/action/validate-action
#        with:
#          role-to-assume: ${{ env.role-to-assume }}
#          role-session-name: ${{ env.role-session-name }}





