name: 'Deploy prod Infra'
on:
  push:
    branches:
      - main
jobs:
  terragrunt-action:
    strategy:
      matrix:
        env: [""]
        aws_region: [""]
        include:
          - env: dev
            aws-region: us-east-1
            aws-account-id: 733051034790
            aws-role: terragrunt
            
          - env: prod
            aws-region: cn-northwest-1
            aws-account-id: 527109613237
            aws-role: terragrunt

    name: init packages
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: terragrunt packages
        uses: ./.github/action/terragrunt-action
        with:
          role-to-assume: arn:aws:iam::${{ matrix.aws-account-id }}:role/${{ matrix.aws-role }}
          role-session-name: github-action
          aws-region: ${{ matrix.aws-region }}
          env: ${{ matrix.env }}
