name: 'checkov'
on:
  push:
    branches:
      - main
    paths-ignore:
      - makefile
      - images/*
      - README.md
jobs:
  infracost-action:
    name: init packages
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: checkov validate terraform modules
        uses: ./.github/action/checkov-action

