name: pull request build

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - makefile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3




