name: Pull Request Build

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - makefile

jobs:
  terrascan:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: terrascan
        continue-on-error: true
        uses: ./.github/action/terrascan-action

  checkov:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: checkov check
        continue-on-error: true
        uses: ./.github/action/checkov-action

  tfsec:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: tfsec
        continue-on-error: true
        uses: ./.github/action/tfsec-action


  terragrunt-infracost-action:
    strategy:
      matrix:
        include:
          - env-dir: dev
            aws-region: us-east-1
            aws-account-id: 733051034790
            aws-role: terragrunt
            aws: aws

          - env-dir: prod
            aws-region: cn-north-1
            aws-account-id: 527109613237
            aws-role: terragrunt
            aws: aws-cn

          - env-dir: stage
            aws-region: ap-southeast-1
            aws-account-id: 594962198840
            aws-role: terragrunt
            aws: aws

    runs-on: ubuntu-latest
    continue-on-error: true

    permissions:
      id-token: write
      contents: write
      actions: write
      security-events: write
      pull-requests: write

    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: infracost packages
        uses: ./.github/action/infracost-action
        with:
          role-to-assume: arn:${{ matrix.aws }}:iam::${{ matrix.aws-account-id }}:role/${{ matrix.aws-role }}
          role-session-name: github-action
          aws-region: ${{ matrix.aws-region }}
          env-dir: ${{ matrix.env-dir }}
          infracost_api_key: ${{ secrets.INFRACOST_API_KEY }}
          create_pr: 'true'

  infracost-report:
    needs:
      - terragrunt-infracost-action
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      actions: write
      security-events: write
      pull-requests: write
    steps:
      - name: Setup Infracost
        # https://github.com/infracost/actions
        # https://github.com/infracost/actions/tree/master/setup for other inputs
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: download-artifact
        uses: actions/download-artifact@v3
        with:
          name: infracost
          path: /tmp

      - name: find download file
        run: ls -R
        working-directory: /tmp

      - name: file find action
        id: fetch
        uses: Rishabh510/Path-lister-action@master
        with:
          path: "/tmp/"
          type: ".json"

      - name: Output results
        shell: bash
        run: |
          echo "Found ${{ steps.fetch.outputs.path_count }} file(s) with this extension:"
          for i in ${{ steps.fetch.outputs.paths }}; do
          echo $i
          done

      - name: concat the infracost result
        run: |
          infracost output -path "/tmp/infracost-*.json" --format json --out-file /tmp/infracost.json

      - name: Post Infracost comment
        run: |
          infracost comment github --path=/tmp/infracost.json \
                                      --repo=$GITHUB_REPOSITORY \
                                      --github-token=${{github.token}} \
                                      --pull-request=${{github.event.pull_request.number}} \
                                      --behavior=update

          










