name: pull request build

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - makefile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: setup docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-single-buildx-${{ steps.short-sha.outputs.sha }}
          restore-keys: |
            ${{ runner.os }}-single-buildx

      - name: docker build
        run: |
          docker buildx build . --file docker/Dockerfile-lambda --platform linux/arm64 --cache-from type=local,src=/tmp/.buildx-cache --cache-to type=local,dest=/tmp/.buildx-cache-new
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
          

